- .gitignore
- LICENSE
- helm/move2kube/Chart.yaml
- helm/move2kube/README.md
- helm/move2kube/templates/NOTES.txt
- helm/move2kube/templates/data-pvcclaim1-persistentvolumeclaim.yaml
- helm/move2kube/templates/move2kube-scc.yaml
- helm/move2kube/templates/move2kubeapi-service.yaml
- helm/move2kube/templates/move2kubeapi-statefulset.yaml
- helm/move2kube/templates/move2kubeapiheadless-service.yaml
- helm/move2kube/templates/move2kubeui-deployment.yaml
- helm/move2kube/templates/move2kubeui-ingress.yaml
- helm/move2kube/templates/move2kubeui-service.yaml
- helm/move2kube/templates/service_account.yaml
- helm/move2kube/values.yaml
> Add move2kube helm chart

- config/crd/bases/konveyor.openshift.io_move2kubes.yaml
- config/crd/kustomization.yaml
- config/rbac/move2kube_editor_role.yaml
- config/rbac/move2kube_viewer_role.yaml
- config/rbac/role.yaml
- config/samples/charts_v1alpha1_move2kube.yaml
> Change group

- code-of-conduct.md
- contributing.md
> Add code of conduct

- helm-charts/move2kube/templates/move2kubeapi-service.yaml
- helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml
- helm-charts/move2kube/templates/move2kubeapiheadless-service.yaml
- helm-charts/move2kube/templates/move2kubeui-deployment.yaml
- helm-charts/move2kube/templates/move2kubeui-ingress.yaml
- helm-charts/move2kube/templates/move2kubeui-service.yaml
> Use release name in ingress path

- config/crd/bases/konveyor.openshift.io_move2kubes.yaml
- config/crd/kustomization.yaml
- config/rbac/move2kube_editor_role.yaml
- config/rbac/move2kube_viewer_role.yaml
- config/rbac/role.yaml
- config/samples/konveyor_v1alpha1_move2kube.yaml
- watches.yaml
> Update group name to konveyor.io

- README.md
- bundle/manifests/move2kube-operator.clusterserviceversion.yaml
- config/manifests/bases/move2kube-operator.clusterserviceversion.yaml
> Fix Readme

- README.md
- helm-charts/move2kube/README.md
> Update urls in readme

- .github/workflows/build.yml
- .github/workflows/release.yml
- bundle/manifests/move2kube-operator.clusterserviceversion.yaml
- config/manifests/bases/move2kube-operator.clusterserviceversion.yaml
> Add support for Bundle image push

- .github/workflows/build.yml
- .github/workflows/release.yml
> Fix quay repo

- helm-charts/move2kube/templates/NOTES.txt
- helm-charts/move2kube/templates/move2kubeui-ingress.yaml
- helm-charts/move2kube/values.yaml
> Add tls support

- .github/workflows/assignproject.yml
- .gitignore
> Autoassign issue to project

- .github/workflows/assignproject.yml
- .github/workflows/release.yml
- .github/workflows/tag.yml
- .grenrc.js
> fix: release workflow to match cli release workflow

- .github/workflows/assignproject.yml
- .github/workflows/build.yml
- .github/workflows/prbuild.yml
- .github/workflows/release.yml
> fix: typo in slack notification and reformat workflow files

- helm-charts/move2kube/values.yaml
> fix: ingress host and secret to be more generic

- .github/workflows/build.yml
- .github/workflows/prbuild.yml
- contributing.md
> chore: Rename default branch to main

- helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml
> fix: Change default dir for move2kube image to workspace

- .github/workflows/build.yml
- .github/workflows/labelpr.yml
- .github/workflows/prbuild.yml
- .github/workflows/release.yml
- .github/workflows/tag.yml
- .grenrc.js
> ci: clean up workflows to work together across multiple repos

- helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml
> feat: Support executing podman inside api container

- helm-charts/move2kube/templates/move2kube-scc.yaml
> fix: Support privileged containers in Openshift using scc

- .github/workflows/release.yml
> ci: fix bug the branch name refs/heads/main is being used instead of the tag

- .github/workflows/release.yml
- Makefile
- bundle/manifests/move2kube-operator.clusterserviceversion.yaml
- config/manifests/bases/move2kube-operator.clusterserviceversion.yaml
- helm-charts/move2kube/Chart.yaml
- helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml
- helm-charts/move2kube/templates/move2kubeui-deployment.yaml
- helm-charts/move2kube/values.yaml
> ci: package and release helm charts

- Makefile
> ci: fix sed regex

- Makefile
- helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml
- helm-charts/move2kube/templates/move2kubeui-deployment.yaml
> fix: helm install gives template error

- README.md
> chore: add usage instructions to README.md

- .github/workflows/release.yml
- .grenrc.js
- README.md
- bundle/manifests/move2kube-operator.clusterserviceversion.yaml
- config/manifests/bases/move2kube-operator.clusterserviceversion.yaml
- helm-charts/move2kube/README.md
> chore: update the index.yaml url since we changed hosting

- helm-charts/move2kube/templates/move2kube-scc.yaml
- helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml
- helm-charts/move2kube/values.yaml
> fix: Make privileged optional

- README.md
> chore: add link to sample auth.json in move2kube-demos

- helm-charts/move2kube/templates/move2kube-api-persistent-volume-claim.yaml
- helm-charts/move2kube/templates/move2kube-api-stateful-set.yaml
- helm-charts/move2kube/templates/move2kube-route.yaml
- helm-charts/move2kube/templates/move2kube-security-context-contraints.yaml
- helm-charts/move2kube/templates/move2kube-service-account.yaml
- helm-charts/move2kube/templates/move2kube-ui-deployment.yaml
- helm-charts/move2kube/templates/move2kube-ui-ingress.yaml
- helm-charts/move2kube/templates/move2kube-ui-persistent-volume-claim.yaml
- helm-charts/move2kube/values.yaml
> feat: allow more customizations for the Helm chart

- README.md
- helm-charts/move2kube/README.md
- helm-charts/move2kube/values.schema.json
> chore: update the docs to reflect the new templates and values.yaml
